import "./globals.css";


import { Roboto } from 'next/font/google'

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})


export const metadata = {
  title: "my app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body
        className={`${roboto.className}  antialiased`}
      >
       
        {children}
       
      </body>
    </html>
  );
}
